on: [push]
jobs:
  Build-Release-Windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: ls -LR
        run: Get-ChildItem -Recurse | Format-Table -Property Mode, LastWriteTime, Length, FullName

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.5

      - name: Install RSRC
        run: go install github.com/akavel/rsrc@latest

      - name: Build Win64
        run: make

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            setup.zip