on: [push]
jobs:
  Build-Release-Windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
#        with:
#          go-version: ^1
      - name: Install RSRC
        run: go install github.com/akavel/rsrc@latest

      - name: Build Win64
        run: make

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            setup.zip